language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install -r test-requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
# command to run tests
script:
  - py.test
after_success:
  - coveralls
